# Generated by Django 5.1.4 on 2024-12-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_category_created_at_category_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systeminfo",
            name="version",
        ),
        migrations.AddField(
            model_name="systeminfo",
            name="seo_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="systeminfo",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="systeminfo",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
