# Generated by Django 5.1.4 on 2024-12-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_remove_systeminfo_version_systeminfo_seo_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systeminfo",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="systeminfo",
            name="updated_at",
        ),
    ]
